#!/busybox sh
mount -t devtmpfs devtmpfs /dev
mkdir -p .o/ro .o/{usr,etc,home}-{ov,wk}
mv .o .o_
mkdir .o
mount -t tmpfs tmpfs /.o
mv .o_/* .o
rm -r .o_
cd .o
mount -t squashfs -o loop,ro /ro.sqfs ro
mount -t overlay overlay -o lowerdir=ro/usr,upperdir=usr-ov,workdir=usr-wk /usr
mount -t overlay overlay -o lowerdir=ro/etc,upperdir=etc-ov,workdir=etc-wk /etc
mount -t overlay overlay -o lowerdir=ro/home,upperdir=home-ov,workdir=home-wk /home
exec /sbin/init
echo fallback
exec /busybox sh
