#!/busybox sh
mount -t devtmpfs devtmpfs /dev
mkdir -p .o/ro .o/{usr,etc,home}-{ov,wk}
mv .o .o_
mkdir .o
mount -t tmpfs tmpfs /.o
mv .o_/* .o
rm -r .o_
cd .o
mount -t squashfs -o loop,ro /ro.sqfs ro
mount -t overlay overlay -o index=off,metacopy=off,lowerdir=ro/usr,upperdir=usr-ov,workdir=usr-wk /usr
mount -t overlay overlay -o index=off,metacopy=off,lowerdir=ro/etc,upperdir=etc-ov,workdir=etc-wk /etc
mount -t overlay overlay -o index=off,metacopy=off,lowerdir=ro/home,upperdir=home-ov,workdir=home-wk /home
if [ -z "$zramsize" ]; then
	zramsize="16M"
fi
if [ "$zramsize" != "0" ]; then
	mount -t sysfs sys /sys
	/sbin/modprobe zram
	cd /sys/block/zram0
	echo $zramsize > disksize
	mkswap /dev/zram0
	swapon -p 10 /dev/zram0
	cd /
	umount /sys
fi
exec /sbin/init
echo fallback
exec /busybox sh
