#!/busybox sh
mount -t devtmpfs devtmpfs /dev
mkdir -p .o/ro .o/{usr,etc,home}-{ov,wk}
mv .o .o_
mkdir .o
mount -t tmpfs tmpfs /.o
mv .o_/* .o
rm -r .o_
cd .o
mount -t squashfs -o loop,ro /ro.sqfs ro
mount -t overlay overlay -o index=off,metacopy=off,lowerdir=ro/usr,upperdir=usr-ov,workdir=usr-wk /usr
mount -t overlay overlay -o index=off,metacopy=off,lowerdir=ro/etc,upperdir=etc-ov,workdir=etc-wk /etc
mount -t overlay overlay -o index=off,metacopy=off,lowerdir=ro/home,upperdir=home-ov,workdir=home-wk /home
mount -t proc proc /proc
ZRAMSIZE=$(tr ' ' '\n' < /proc/cmdline | grep 'zramsize=' | cut -d = -f 2-)
if [ -z "$ZRAMSIZE" ]; then
	ZRAMSIZE="16M"
fi
if [ "$ZRAMSIZE" != "0" ]; then
	mount -t sysfs sys /sys
	/sbin/modprobe zram
	cd /sys/block/zram0
	echo $ZRAMSIZE > disksize
	mkswap /dev/zram0
	swapon -p 10 /dev/zram0
	cd /
	umount /sys
fi
umount /proc
exec /sbin/init
echo fallback
exec /busybox sh
