#!/bin/sh

do_overlay_mount() {
	mkdir -p $1-ro $1-wk $1-ov
	mount --bind /$1 $1-ro
	mount -t overlay overlay -o lowerdir=$1-ro,upperdir=$1-ov,workdir=$1-wk /$1
}

start() {
	grep /dev/root /proc/mounts | grep -q squashfs && (
		echo 'Setting up tmpfs overlays (/etc,/root,/usr,/home)'
		mkdir -p /tmp/.o
		cd /tmp/.o

		do_overlay_mount etc
		do_overlay_mount root
		do_overlay_mount usr
		do_overlay_mount home
	)
	return 0
}

stop() {
	return 0
}

restart() {
	return 0
}

case "$1" in
	start|stop|restart)
		"$1";;
	reload)
		# Restart, since there is no true "reload" feature.
		restart;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
esac
