#!/bin/sh

start() {
	screen -dmS bgscreen
	return 0
}

stop() {
	screen -XS bgscreen quit
	return 0
}

restart() {
	stop
	sleep 1
	start
	return 0
}

case "$1" in
	start|stop|restart)
		"$1";;
	reload)
		# Restart, since there is no true "reload" feature.
		restart;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
esac
