#!/bin/sh

start() {
	echo "Login as root or user (no password)."
	echo "System (& kernel) logs are in VT7 (Alt-F7) or /var/log/messages"
	return 0
}

stop() {
	return 0
}

restart() {
	return 0
}

case "$1" in
	start|stop|restart)
		"$1";;
	reload)
		# Restart, since there is no true "reload" feature.
		restart;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
esac
