#!source-me/sh
echo "Setting up overlay..."
cd .o
mkdir -p ro usr-ov usr-wk etc-ov etc-wk
mount -t squashfs -o loop,ro "$1" ro
mount -t overlay overlay -o lowerdir=ro/usr,upperdir=usr-ov,workdir=usr-wk ../usr
mount -t overlay overlay -o lowerdir=ro/etc,upperdir=etc-ov,workdir=etc-wk ../etc
