#!/bin/sh

start() {
	echo "Launching net_daemon.sh"
	(/usr/bin/net_daemon.sh &)&
	return 0
}

stop() {
	PIDFILE=/tmp/netdaemon-pid
	if [ -e "$PIDFILE" ]; then
		kill -KILL $(cat /tmp/netdaemon-pid)
		rm -f /tmp/netdaemon-pid
	fi
	return 0
}

restart() {
	stop
	sleep 1
	start
	return 0
}

case "$1" in
	start|stop|restart)
		"$1";;
	reload)
		# Restart, since there is no true "reload" feature.
		restart;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
esac
