I586CON_SAVESTATE_VERSION = 0.1
I586CON_SAVESTATE_SITE = $(BR2_EXTERNAL_I586CON_PATH)/package/i586con-savestate/pkgsrc
I586CON_SAVESTATE_SITE_METHOD = local
I586CON_SAVESTATE_SETUP_TYPE = setuptools

$(eval $(python-package))
