#!/busybox sh
. /startup
. /tmpfsmnt "-o size=75%"
. /mountxsave /mnt/cd /mnt/cd/img/save.tgz
echo "Copying read-only image to RAM..."
mkdir -p .o/Z
[ -e /dev/zram0 ] && mount -t ramfs ramfs .o/Z
cp cd/img/rootfs.img .o/Z/ro.cpio
[ -e cd/img/ro-size ] && truncate -s $(cat cd/img/ro-size) .o/Z/ro.cpio
. /overlay "Z/ro.cpio"
cd /mnt
[ -x preinit.sh ] && ./preinit.sh
umount /mnt/cd
. /switch
