#!source-me/sh
if [ -z "$zramsize" ]; then
	zramsize="16M"
fi
if [ "$zramsize" != "0" ] && [ -e /zram/load ]; then
	cd /zram
	. ./load
	cd /sys/block/zram0
	echo $zramsize > disksize
	mkswap /dev/zram0
	swapon -p 10 /dev/zram0
	cd /
fi
