#!source-me/sh
ZRAMSIZE=$(tr ' ' '\n' < /proc/cmdline | grep 'zramsize=' | cut -d = -f 2-)
if [ -z "$ZRAMSIZE" ]; then
	ZRAMSIZE="16M"
fi
if [ "$ZRAMSIZE" != "0" ] && [ -e /zram/load ]; then
	cd /zram
	. ./load
	cd /sys/block/zram0
	echo $ZRAMSIZE > disksize
	mkswap /dev/zram0
	swapon -p 10 /dev/zram0
	cd /
fi
