#!/busybox sh
mount -t devtmpfs devtmpfs /dev
mount -t proc proc proc
mount -t sysfs sys sys
mount -t tmpfs tmpfs /mnt
mkdir -p /mnt/cd
cd /mnt

#set -x
ROOT=$(tr ' ' '\n' < /proc/cmdline | grep 'root=' | cut -d = -f 2-)
if echo $ROOT | grep -q "="; then
	FIND_TYPE="$(echo $ROOT | cut -d = -f 1)="
	FIND_VAL=$(echo $ROOT | cut -d = -f 2-)
	FIND_DEV="NODEVICE"
else
	FIND_DEV=$ROOT
	FIND_TYPE="NOTYPE"
	FIND_VAL="NOVALUE"
fi

TRIES=0
FOUND=0
while [ $TRIES -lt 40 ]; do
	blkid > /blkid.txt
	while read dev; do
		DEVICE=$(echo $dev | cut -d : -f 1)
		if [ "$DEVICE" = "$FIND_DEV" ]; then
			FOUND=1
			break
		fi
		INFO=$(echo $dev | cut -d : -f 2)
		while [ "$INFO" != "" ]; do
			TYPE=$(echo $INFO | cut -d \" -f 1)
			VAL=$(echo $INFO | cut -d \" -f 2)
			INFO=$(echo $INFO | cut -d \" -f 3-)
			if [ "$FIND_TYPE" = "$TYPE" ]; then
				if [ "$FIND_VAL" = "$VAL" ]; then
					FOUND=1
					break
				fi
			fi
		done
	done < /blkid.txt
	TRIES=$((TRIES + 1))
	if [ $FOUND -gt 0 ]; then
		break
	fi
	sleep 0.25s
done
if [ $FOUND -gt 0 ]; then
	mount -o ro $DEVICE cd
fi
if [ ! -e cd/boot ]; then
	echo "Couldn't find media. Mount it on /mnt/cd if you can..."
	sh
fi

tar xf cd/img/save.tgz
cd .o
mkdir -p ro usr-ov usr-wk etc-ov etc-wk
mount -t squashfs -o loop,ro /mnt/cd/img/ro.sqf ro
mount -t overlay overlay -o lowerdir=ro/usr,upperdir=usr-ov,workdir=usr-wk ../usr
mount -t overlay overlay -o lowerdir=ro/etc,upperdir=etc-ov,workdir=etc-wk ../etc
cd /
umount sys
umount proc
mount --move /dev /mnt/dev
exec /busybox switch_root -c dev/console /mnt /sbin/init "$@"
